[build]
  functions = "netlify/functions"
  publish = "src"

[dev]
  functions = "netlify/functions"
  publish = "src"
  autoLaunch = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200